import React, { useState, useEffect } from 'react';
import { Award, Terminal, HardDrive, Cpu } from 'lucide-react';

interface BenchmarkMatrixProps {
  isOpen: boolean;
  onClose?: () => void;
}

interface PromptResult {
  timings_verbatim: { predicted_n: number; predicted_ms: number; predicted_per_second: number };
  content: string;
  identical_to_baseline: boolean | null;
}

interface ConfigResult {
  config: string;
  cmd: string[] | null;
  started: string | null;
  git_head: string | null;
  free_ram_gb_before_launch: number | null;
  smi_after_load_raw: string | null;
  log_excerpt: string[];
  gpu_layers: { offloaded: number; total: number } | null;
  prompts: Record<string, PromptResult>;
  pooled_tok_s?: number;
  tokens?: number;
  gen_seconds?: number;
  draft_n: number;
  draft_accepted: number;
}

// Shape of benchmarks/runs/results.json, generated by benchmarks/summarize_runs.py
// from raw llama-server captures. This component holds no measured values itself.
interface ProofPayload {
  generated_by: string;
  model: string;
  baseline_config: string;
  hardware_raw: string | null;
  configs: ConfigResult[];
}

type Tab = 'results' | 'logs' | 'hardware' | 'json';

export const BenchmarkMatrix: React.FC<BenchmarkMatrixProps> = ({ isOpen }) => {
  const [proof, setProof] = useState<ProofPayload | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState<Tab>('results');
  const [selected, setSelected] = useState<string>('');

  useEffect(() => {
    if (!isOpen) return;
    const load = async () => {
      try {
        const res = await fetch('/proof');
        const data = await res.json();
        if (Array.isArray(data.configs) && data.configs.length > 0) {
          setProof(data);
          setError(null);
          setSelected((s) => s || data.baseline_config || data.configs[0].config);
        } else {
          setProof(null);
          setError('No proof on disk. Run: python benchmarks/raw_capture.py matrix && python benchmarks/summarize_runs.py');
        }
      } catch {
        setProof(null);
        setError('Could not reach the HARNESS server /proof endpoint.');
      }
    };
    load();
  }, [isOpen]);

  if (!isOpen) return null;

  const tabBtn = (t: Tab, label: string) => (
    <button
      key={t}
      onClick={() => setActiveTab(t)}
      className={`px-3 py-1 rounded-lg transition-all font-mono text-[11px] ${
        activeTab === t ? 'bg-cyan-600 text-white font-bold' : 'text-slate-400 hover:text-slate-200'
      }`}
    >
      {label}
    </button>
  );

  const cur = proof?.configs.find((c) => c.config === selected) ?? proof?.configs[0];
  const baseline = proof?.configs.find((c) => c.config === proof.baseline_config);

  return (
    <div className="bg-[#0b0f19] border border-cyan-500/40 rounded-2xl p-4 my-2 shadow-2xl shadow-cyan-950/30">
      <div className="flex flex-col md:flex-row md:items-center justify-between pb-3 border-b border-slate-800 gap-2">
        <div className="flex items-center gap-2">
          <div className="p-1.5 rounded-lg bg-cyan-500/20 text-cyan-400">
            <Award className="w-4 h-4" />
          </div>
          <div>
            <h2 className="text-xs font-bold uppercase tracking-wider text-slate-100">
              Measured Benchmark Proof ({proof?.model ?? 'llama3.1:70b-instruct-q2_K'})
            </h2>
            <p className="text-[11px] text-slate-400">
              Every value is computed from raw llama-server captures in benchmarks/runs/. Nothing is hardcoded in this UI.
            </p>
          </div>
        </div>
        <div className="flex items-center gap-1.5 bg-[#0f1422] p-1 rounded-xl border border-slate-800 text-xs">
          {tabBtn('results', 'Results')}
          {tabBtn('logs', 'Raw log lines')}
          {tabBtn('hardware', 'Hardware (raw)')}
          {tabBtn('json', 'Raw JSON')}
        </div>
      </div>

      {error && <div className="mt-3 p-3 text-xs font-mono text-amber-300 bg-amber-950/20 rounded-xl border border-amber-700/40">{error}</div>}

      {proof && cur && (
        <div className="mt-3">
          {activeTab === 'results' && (
            <div className="overflow-x-auto rounded-xl border border-slate-800">
              <table className="w-full text-left text-[11px] font-mono">
                <thead>
                  <tr className="bg-[#111827] text-slate-400 border-b border-slate-800">
                    <th className="py-2 px-3">config</th>
                    <th className="py-2 px-3">GPU layers</th>
                    <th className="py-2 px-3">tok/s (pooled)</th>
                    <th className="py-2 px-3">per prompt</th>
                    <th className="py-2 px-3">draft accepted</th>
                    <th className="py-2 px-3">output vs baseline</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-800/60">
                  {proof.configs.map((c) => {
                    const ps = Object.entries(c.prompts);
                    const same = ps.filter(([, p]) => p.identical_to_baseline !== null);
                    return (
                      <tr key={c.config} className={c.config === proof.baseline_config ? 'bg-emerald-950/20' : ''}>
                        <td className="py-2 px-3 text-slate-200">
                          {c.config}
                          {c.config === proof.baseline_config && <span className="text-emerald-400"> (baseline)</span>}
                        </td>
                        <td className="py-2 px-3 text-slate-300">{c.gpu_layers ? `${c.gpu_layers.offloaded}/${c.gpu_layers.total}` : 'n/a'}</td>
                        <td className="py-2 px-3 text-emerald-400 font-bold">{c.pooled_tok_s !== undefined ? c.pooled_tok_s.toFixed(3) : 'failed'}</td>
                        <td className="py-2 px-3 text-slate-400">
                          {ps.map(([n, p]) => `${n} ${p.timings_verbatim.predicted_per_second.toFixed(2)}`).join(' / ') || '-'}
                        </td>
                        <td className="py-2 px-3 text-slate-300">
                          {c.draft_n ? `${c.draft_accepted}/${c.draft_n} (${((100 * c.draft_accepted) / c.draft_n).toFixed(0)}%)` : 'n/a'}
                        </td>
                        <td className="py-2 px-3 text-slate-400">
                          {same.length ? same.map(([n, p]) => `${n}: ${p.identical_to_baseline ? 'identical' : 'differs'}`).join(', ') : 'reference'}
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
              {baseline?.pooled_tok_s !== undefined && (
                <div className="p-2 text-[10px] text-slate-500 bg-slate-900/60 border-t border-slate-800">
                  Baseline = {proof.baseline_config}. Greedy decoding, same prompts and token budget for every row. Speculative rows are a separate
                  experiment and their speedup depends on the content.
                </div>
              )}
            </div>
          )}

          {activeTab === 'logs' && (
            <div className="rounded-xl bg-[#090d16] border border-slate-800 p-3 font-mono text-[11px]">
              <div className="flex items-center gap-2 pb-2 mb-2 border-b border-slate-800/80 text-xs text-cyan-400">
                <Terminal className="w-3.5 h-3.5" />
                <select value={selected} onChange={(e) => setSelected(e.target.value)} className="bg-slate-900 text-slate-200 rounded px-1">
                  {proof.configs.map((c) => (
                    <option key={c.config} value={c.config}>{c.config}</option>
                  ))}
                </select>
                <span className="text-slate-500">verbatim llama-server lines (filtered by keyword; full file in repo)</span>
              </div>
              {cur.cmd && <div className="text-amber-300 whitespace-pre-wrap break-all pb-2">{cur.cmd.join(' ')}</div>}
              <div className="space-y-0.5 overflow-x-auto max-h-60">
                {cur.log_excerpt.map((l, i) => (
                  <div key={i} className="text-slate-300 whitespace-pre">{l}</div>
                ))}
              </div>
            </div>
          )}

          {activeTab === 'hardware' && (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3 font-mono text-xs">
              <div className="p-3 rounded-xl bg-[#111624] border border-slate-800">
                <div className="font-bold text-slate-200 flex items-center gap-1.5 pb-1 border-b border-slate-800">
                  <HardDrive className="w-4 h-4 text-amber-400" /> Host (raw capture)
                </div>
                <pre className="text-[10px] text-slate-300 whitespace-pre-wrap mt-2 max-h-60 overflow-auto">{proof.hardware_raw ?? 'benchmarks/runs/hardware.txt not found'}</pre>
              </div>
              <div className="p-3 rounded-xl bg-[#111624] border border-slate-800">
                <div className="font-bold text-slate-200 flex items-center gap-1.5 pb-1 border-b border-slate-800">
                  <Cpu className="w-4 h-4 text-cyan-400" /> nvidia-smi after load ({cur.config})
                </div>
                <pre className="text-[10px] text-slate-300 whitespace-pre-wrap mt-2 max-h-60 overflow-auto">{cur.smi_after_load_raw ?? 'not captured'}</pre>
              </div>
            </div>
          )}

          {activeTab === 'json' && (
            <div className="rounded-xl bg-[#090d16] border border-slate-800 p-3 font-mono text-[11px] overflow-x-auto max-h-60">
              <pre className="text-emerald-300">{JSON.stringify(proof, null, 2)}</pre>
            </div>
          )}
        </div>
      )}
    </div>
  );
};
